In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
# Vectorized function

In [3]:
import time
a=np.random.rand(100000)
b=np.random.rand(100000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()
#d=1000*(toc-tic)
print("Vectorized version:"+str(1000*(toc-tic))+"ms")
#print(c)
#print(d)

#Non-Vectorized function

c=0
tic=time.time()
for i in range (100000):
    c+=a[i]*b[i]
toc=time.time()
print(c)
print("for loop:"+str(1000*(toc-tic))+"ms")


Vectorized version:37.902116775512695ms
24995.72641143208
for loop:60.836076736450195ms


In [4]:
#Non-Vectorized function

In [5]:
c=0
tic=time.time()
for i in range (100000):
    c+=a[i]*b[i]
toc=time.time()
print(c)
print("for loop:"+str(1000*(toc-tic))+"ms")

24995.72641143208
for loop:46.872615814208984ms


In [6]:
import numpy as np
A= np.array([[56, 0.0, 4.4, 68],
            [1.2, 104, 52, 8],
            [1.8, 135, 99, .9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [7]:
cal=A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [8]:
p=100*A/cal.reshape(1,4)
print(p)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
a=np.random.randn(4,3)
b=np.random.randn(3,2)
c=a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [10]:
print(c.shape)

()


In [11]:
a=np.random.randn(12288,150) # a.shape = (12288, 150)a.shape=(12288,150)

b = np.random.randn(150, 45) # b.shape = (150, 45)$$

c = np.dot(a,b) 

In [12]:
c.shape

(12288, 45)

In [13]:
a=np.random.randn(3,3)

b = np.random.randn(3, 1)

c = a*b

In [14]:
c.shape

(3, 3)

In [15]:
print(c)

[[-0.18233654  0.27030185 -0.02095891]
 [ 1.06267188 -0.87687961  0.74368417]
 [ 0.32163401  0.84135333 -0.09849549]]
