In [5]:
# l1 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l1 = norm(a,2)
print(l1)

[1 2 3]
3.7416573867739413


In [2]:
# l2 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


In [7]:
# max norm of a vector
from numpy import inf
from numpy import array
from numpy.linalg import norm
a = array([1, 9, 3])
print(a)
maxnorm = norm(a, inf)
print(maxnorm)

[1 9 3]
9.0


In [8]:
def frobenius_norm(A):
    total = 0
    for row in A:
        for i in row:
            total += i**2
            
    return total **0.5

def inf_norm(A):
    max_row = 0
    for i in A:
        sum_ = 0
        for j in i:
            sum_ += abs(j)
        if sum_ > max_row:
            max_row = sum_
    
    return max_row


def l1_norm(A):
    max_column = 0 
    for i in zip(*b):
        sum_ = 0 
        for j in i:
            sum_ += abs(j)
        if sum_ > max_column:
            max_column = sum_
    return max_column

In [11]:
print(l1_norm)
print(frobenius_norm)
print(inf_norm)

<function l1_norm at 0x000001D5CA5713A0>
<function frobenius_norm at 0x000001D5CA571670>
<function inf_norm at 0x000001D5CA571700>


In [12]:
import gurobipy as gp
from gurobipy import GRB

# Create a new model
m = gp. Model (" mip1 ")
# Create variables
x = m. addVar ( vtype =GRB.BINARY , name ="x")
y = m. addVar ( vtype =GRB.BINARY , name ="y")
z = m. addVar ( vtype =GRB.BINARY , name ="z")
# Set objective
m. setObjective (x + y + 2 * z, GRB. MAXIMIZE )
# Add constraint : x + 2 y + 3 z <= 4
m. addConstr (x + 2 * y + 3 * z <= 4, "c0")
# Add constraint : x + y >= 1
m. addConstr (x + y >= 1, "c1")
# Optimize model
m. optimize ()

model_fingerprint = m.fingerprint
print("query_finger_print")
print(model_fingerprint)

ModuleNotFoundError: No module named 'gurobipy'